export const SET_RESERVOIRLIST = 'SET_RESERVOIRLIST'

export const SET_WARNCONFIG = 'SET_WARNCONFIG'

export const SET_DOCUMENT_TITLE= 'SET_DOCUMENT_TITLE'

export const SET_FILE_PATH_URL= 'SET_FILE_PATH_URL'